### ISSUE TITLE
Add a warning if user chose a big group (>8 people)

### ISSUE THREAD

**Issue by ReflexLevel0** [Karl255/UcenikShuffle#13]

**Comment by Karl255** [comment]
Fixed in [this](https://github.com/Karl255/UcenikShuffle/pull/7/commits/9fcf95037e31f7694695ed1d6e03cdffe265f24e) commit. Although maybe the numbers should be tweaked a little (I tried to find an approximate formula for the computational complexity, but wasn't successful). For now, this is good.
