### ISSUE TITLE
Fast mode

### ISSUE THREAD

**Issue by ReflexLevel0** [Karl255/UcenikShuffle#17]
Add fast mode which would calculate an approximation for the best sitting schedule. The problem is that with a group of 10 students there can be 10 billion combinations which takes forever to load. With "fast mode" the algorithm should calculate the schedule with less precision but in much lower time (I don't have any idea how this would work, but it might be an interesting thing to do)

**Comment by Karl255** [comment]
An approximation would be completely useless. Also it'd make the app needlessly complex for what it needs to do.
